# Generated by Django 6.0.6 on 2026-06-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
