# Generated by Django 6.0.6 on 2026-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
